data: 
  data_dir: /fast_scratch_1/jbohm/train_testing_data/train_3/
  num_train_files: 304
  num_val_files: 101
  batch_size: 1024
  shuffle: False
  num_procs: 32
  preprocess: True
  output_dir: /fast_scratch_1/jbohm/train_testing_data/train_3/
  already_preprocessed: True
  cell_geo_file: /data/atlas/data/allCellTruthv1/pi0/user.mswiatlo.27153451.OutputStream._000001.root
model:
  block_type: graphnet
  concat_input: true
  edge_block_opt: {use_edges: true, use_globals: true, use_receiver_nodes: true, use_sender_nodes: true}
  global_block_opt: {use_edges: false, use_globals: true, use_nodes: true}
  latent_size: 64
  node_block_opt: {use_globals: true, use_nodes: true, use_received_edges: true, use_sent_edges: false}
  num_blocks: 4
  num_layers: 4
  reducer: mean
training: 
  alpha: .75 
  epochs: 10
  gpu: 4
  learning_rate: 0.001
  log_freq: 100
  save_dir: /fast_scratch_1/jbohm/train_testing_data/train_3/
